from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

try:
    from pipeline.generate_lookdev import find_shot, load_json
except ModuleNotFoundError:  # Direct `python pipeline/...py` execution.
    from generate_lookdev import find_shot, load_json


ROOT = Path(__file__).resolve().parents[1]


def referenced_actor_ids(shot: dict[str, Any]) -> set[str]:
    ids: set[str] = set()
    camera_target = shot.get("camera", {}).get("target")
    if camera_target and camera_target != "environment":
        ids.add(str(camera_target))

    for action in shot.get("actions", []):
        actor = action.get("actor")
        target = action.get("target")
        if actor and actor != "environment":
            ids.add(str(actor))
        if target and target != "environment":
            ids.add(str(target))
    return ids


def actor_context(scenario: dict[str, Any], shot: dict[str, Any]) -> list[dict[str, Any]]:
    wanted = referenced_actor_ids(shot)
    return [actor for actor in scenario.get("actors", []) if str(actor.get("id")) in wanted]


def review_contract() -> dict[str, Any]:
    return {
        "source_of_truth": [
            "scenario shot semantics",
            "deterministic Three.js staging",
            "registered reusable assets",
        ],
        "composition_authority": "deterministic_preview",
        "lookdev_policy": (
            "The Ollama FLUX frame is a text-generated advisory visual-quality target. It was not generated by editing the "
            "Three.js preview. Never use it to judge actor count, exact blocking, framing, camera placement or continuity. "
            "Use it only for anatomy/silhouette inspiration, material response, lighting, atmosphere, foliage richness and visual hierarchy."
        ),
        "preview_only_dimensions": [
            "actor count and species presence",
            "composition and framing",
            "camera placement and lens intent",
            "actor blocking and interaction geography",
            "occlusion and continuity",
            "foot contact with the actual scene",
            "motion readability",
        ],
        "lookdev_reference_dimensions": [
            "anatomical plausibility and body mass",
            "silhouette quality",
            "continuous neck hip and tail transitions",
            "skin and material realism",
            "eyes teeth gums and oral tissue",
            "lighting and exposure quality",
            "atmosphere and weather readability",
            "environment richness and depth",
            "documentary realism",
        ],
        "patch_policy": [
            "Prefer bounded deterministic scenario/runtime patches for camera, lighting, density and placement defects observed in the preview.",
            "Use requires_agent for reusable anatomy, topology, UV, material, rig or animation defects.",
            "Prefer reusable Blender-master fixes over shot-specific mesh hacks.",
            "Never propose reproducing FLUX hallucinated actors, props, blocking or framing.",
            "Never propose using the FLUX frame as a final video frame.",
        ],
        "result_schema": "schemas/visual_critique_result.schema.json",
        "routing_command": "pipeline/route_visual_critique.py",
    }


def expected_output_schema(shot_id: str) -> dict[str, Any]:
    return {
        "shot_id": shot_id,
        "pass": False,
        "issues": [
            {
                "category": "anatomy|material|animation|camera|lighting|environment|composition|continuity",
                "severity": "low|medium|high|blocking",
                "observation": "...",
                "evidence": "preview_only|scenario|preview_vs_lookdev_quality_reference",
            }
        ],
        "patches": [
            {
                "path": "camera.distance",
                "operation": "set",
                "value": 12.5,
                "reason": "...",
            }
        ],
        "requires_agent": [
            {
                "agent": "asset_designer|animation_director|environment_designer",
                "asset_id": "...",
                "severity": "low|medium|high|blocking",
                "reason": "...",
                "acceptance_criteria": ["..."],
            }
        ],
    }


def build_request_text(package: dict[str, Any]) -> str:
    inputs = package["inputs"]
    return "\n".join(
        [
            f"# Visual critique request: {package['shot_id']}",
            "",
            "Review the deterministic Three.js preview as the authoritative shot result.",
            "Use the FLUX image only as an advisory visual-quality reference for anatomy, materials, lighting, atmosphere and environment richness.",
            "The FLUX image was generated from text, not by editing the preview; ignore any different actor count, blocking, camera or composition in it.",
            "Return JSON matching `expected_output` in the package and `schemas/visual_critique_result.schema.json`.",
            f"Save the completed result as build/critique/{package['scenario_id']}/{package['shot_id']}.result.json.",
            "",
            f"- authoritative preview: {inputs['preview_frame']}",
            f"- advisory FLUX look target: {inputs['lookdev_target']}",
            f"- look-dev prompt: {inputs['lookdev_prompt']}",
            f"- look-dev metadata: {inputs['lookdev_metadata']}",
            "",
            "Focus first on blocking anatomy/topology/motion defects in the real preview, then camera/lighting/environment polish.",
            "For reusable agent work, include a severity and visually verifiable acceptance criteria.",
            "After saving the result, route it through pipeline/route_visual_critique.py.",
        ]
    ) + "\n"


def build_package(
    scenario: dict[str, Any],
    shot: dict[str, Any],
    *,
    preview_dir: Path,
    lookdev_dir: Path,
    output_dir: Path,
    allow_missing_lookdev: bool = False,
) -> tuple[Path, Path]:
    scenario_id = str(scenario.get("scenario_id", "scenario"))
    shot_id = str(shot["id"])
    preview = preview_dir / f"{shot_id}.png"
    target = lookdev_dir / f"{shot_id}.png"
    prompt = lookdev_dir / f"{shot_id}.prompt.txt"
    metadata = lookdev_dir / f"{shot_id}.json"

    if not preview.exists():
        raise FileNotFoundError(f"Missing deterministic preview: {preview}")
    if not allow_missing_lookdev and not target.exists():
        raise FileNotFoundError(f"Missing FLUX look-dev target: {target}")

    lookdev_metadata: dict[str, Any] | None = None
    if metadata.exists():
        try:
            lookdev_metadata = json.loads(metadata.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            raise ValueError(f"Invalid look-dev metadata JSON: {metadata}") from exc

    package: dict[str, Any] = {
        "schema_version": 2,
        "scenario_id": scenario_id,
        "shot_id": shot_id,
        "shot": shot,
        "environment": scenario.get("environment", {}),
        "actors": actor_context(scenario, shot),
        "inputs": {
            "preview_frame": str(preview.resolve()),
            "lookdev_target": str(target.resolve()) if target.exists() else None,
            "lookdev_prompt": str(prompt.resolve()) if prompt.exists() else None,
            "lookdev_metadata": str(metadata.resolve()) if metadata.exists() else None,
        },
        "lookdev_metadata": lookdev_metadata,
        "review_contract": review_contract(),
        "expected_output": expected_output_schema(shot_id),
    }

    output_dir.mkdir(parents=True, exist_ok=True)
    package_path = output_dir / f"{shot_id}.json"
    request_path = output_dir / f"{shot_id}.request.md"
    package_path.write_text(json.dumps(package, indent=2) + "\n", encoding="utf-8")
    request_path.write_text(build_request_text(package), encoding="utf-8")
    return package_path, request_path


def parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Build visual-critic input packages from preview and FLUX look-dev frames.")
    p.add_argument("scenario", type=Path, help="Scenario JSON path")
    p.add_argument("--shot-id", action="append", help="Shot id to package; repeatable. Defaults to all shots.")
    p.add_argument("--preview-dir", type=Path)
    p.add_argument("--lookdev-dir", type=Path)
    p.add_argument("--output-dir", type=Path)
    p.add_argument(
        "--allow-missing-lookdev",
        action="store_true",
        help="Build preview-only packages when a FLUX target is unavailable.",
    )
    return p


def main() -> int:
    args = parser().parse_args()
    scenario_path = args.scenario.resolve()

    try:
        scenario = load_json(scenario_path)
        scenario_id = str(scenario.get("scenario_id", scenario_path.stem))
        preview_dir = (args.preview_dir or ROOT / "build" / "preview" / scenario_id).resolve()
        lookdev_dir = (args.lookdev_dir or ROOT / "build" / "lookdev" / scenario_id).resolve()
        output_dir = (args.output_dir or ROOT / "build" / "critique" / scenario_id).resolve()

        shots = scenario.get("shots", [])
        if args.shot_id:
            shots = [find_shot(scenario, shot_id) for shot_id in args.shot_id]
        if not shots:
            raise ValueError("Scenario contains no shots")

        for shot in shots:
            package_path, request_path = build_package(
                scenario,
                shot,
                preview_dir=preview_dir,
                lookdev_dir=lookdev_dir,
                output_dir=output_dir,
                allow_missing_lookdev=args.allow_missing_lookdev,
            )
            print(f"WROTE {package_path}")
            print(f"WROTE {request_path}")
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
